"""Draft ``ptp4l`` and ``ts2phc`` configuration fragments.

Read this before you use the output:

**These are drafts.** They carry the correct interface names and the correct
PHC device paths, which is the part that a person gets wrong. Nothing else in
them is tuned. Every delay, every priority and every domain number is a default
that you must set from your own network plan.

nicscope writes the file. It never starts the daemon. Section 7.
"""

from __future__ import annotations

from ..model import Interface, Report

BANNER = [
    "# ---------------------------------------------------------------------",
    "# DRAFT, generated by nicscope. NOT TUNED.",
    "#",
    "# The interface names and the PHC device paths are read from the running",
    "# machine and are correct. Every other value is a default. Set the domain",
    "# number, the priorities and the delay mechanism from your network plan",
    "# before you run this on a measurement system.",
    "# ---------------------------------------------------------------------",
]


def render(report: Report) -> str:
    """Both fragments in one document, separated by a file marker."""
    parts = [ptp4l(report), "", ts2phc(report)]
    return "\n".join(parts)


def ptp4l(report: Report) -> str:
    usable = [i for i in report.interfaces if _can_stamp(i)]
    lines = ["# === ptp4l.conf ======================================================"]
    lines.extend(BANNER)
    lines.append(f"# host: {report.host.hostname or 'unknown'}   collected: {report.collected_at}")
    lines.append("")

    if not usable:
        lines.append("# No interface on this host has hardware transmit timestamping.")
        lines.append("# ptp4l would have to run with software timestamping, and that")
        lines.append("# is not good enough for a measurement system.")
        return "\n".join(lines) + "\n"

    one_step = all("one-step-sync" in i.timestamping.tx_types for i in usable)

    lines.append("[global]")
    lines.append("verbose                 1")
    lines.append("time_stamping           hardware")
    lines.append("# 0 is the default PTP domain. Set your own.")
    lines.append("domainNumber            0")
    lines.append("# 0 for two-step, 1 for one-step. One-step removes the Follow_Up.")
    lines.append(f"twoStepFlag             {0 if one_step else 1}")
    lines.append("# E2E is the safe default. Use P2P only when every device supports it.")
    lines.append("delay_mechanism         E2E")
    lines.append("network_transport       UDPv4")
    lines.append("tx_timestamp_timeout    50")
    lines.append("logAnnounceInterval     1")
    lines.append("logSyncInterval         0")
    lines.append("")

    for iface in usable:
        lines.append(f"# {_describe(iface)}")
        lines.append(f"[{iface.name}]")
        for note in _warnings(iface):
            lines.append(f"# warning: {note}")
        lines.append("")

    skipped = [i for i in report.interfaces if not _can_stamp(i)]
    if skipped:
        lines.append("# Left out, no hardware transmit timestamping:")
        for iface in skipped:
            lines.append(f"#   {iface.name}: {_why_not(iface)}")
    return "\n".join(lines) + "\n"


def ts2phc(report: Report) -> str:
    """A fragment for the port that takes the PPS from the GNSS receiver."""
    usable = [i for i in report.interfaces if (i.timestamping.n_ext_ts or 0) > 0]
    lines = ["# === ts2phc.cfg ======================================================"]
    lines.extend(BANNER)
    lines.append("#")
    lines.append("# Run it with an explicit source, for example:")
    lines.append("#   ts2phc -f ts2phc.cfg -s generic -m")
    lines.append("# `generic` means an external PPS on the pin. Use `nmea` when the")
    lines.append("# receiver also gives the time of day on a serial port.")
    lines.append("")

    if not usable:
        lines.append("# No interface on this host has an external timestamp pin.")
        lines.append("# ts2phc cannot take a PPS on this machine. A card with an SDP pin,")
        lines.append("# for example an Intel i210, i225 or i226, is needed.")
        return "\n".join(lines) + "\n"

    lines.append("[global]")
    lines.append("use_syslog              0")
    lines.append("verbose                 1")
    lines.append("# The pulse width of the PPS in nanoseconds. 100 ms is common.")
    lines.append("ts2phc.pulsewidth       100000000")
    lines.append("")

    for iface in usable:
        stamp = iface.timestamping
        device = stamp.phc_device_stable or stamp.phc_device
        lines.append(f"# {_describe(iface)}")
        if not stamp.phc_device_stable:
            lines.append("# warning: this is the numbered path. The number can change across a")
            lines.append("# reboot. Add a udev rule that makes /dev/ptp_<name> and use that.")
        lines.append(f"# PHC device: {device}")
        lines.append(f"[{iface.name}]")
        lines.append("# Pick the pin that carries the PPS. The pin table is in the report.")
        lines.append(f"ts2phc.pin_index        {_extts_pin(iface)}")
        lines.append("ts2phc.channel          0")
        lines.append("ts2phc.extts_polarity   rising")
        lines.append("")
    return "\n".join(lines) + "\n"


# -------------------------------------------------------------- helpers ---
def _can_stamp(iface: Interface) -> bool:
    stamp = iface.timestamping
    return (
        stamp.phc_index is not None
        and stamp.phc_index >= 0
        and "on" in stamp.tx_types
        and bool(stamp.rx_filters)
    )


def _why_not(iface: Interface) -> str:
    stamp = iface.timestamping
    if stamp.phc_index is None:
        return "ethtool -T gave no answer"
    if stamp.phc_index < 0:
        return "no PHC"
    if "on" not in stamp.tx_types:
        return "no hardware transmit timestamp mode"
    return "no hardware receive filter"


def _describe(iface: Interface) -> str:
    parts = [iface.name]
    label = iface.labels.get("user") or iface.labels.get("bios")
    if label:
        parts.append(f'"{label}"')
    if iface.pci and iface.pci.bdf:
        parts.append(iface.pci.bdf)
    if iface.pci and iface.pci.device:
        parts.append(iface.pci.device)
    if iface.permaddr:
        parts.append(iface.permaddr)
    return "  ".join(parts)


def _warnings(iface: Interface) -> list[str]:
    notes: list[str] = []
    if "all" not in iface.timestamping.rx_filters:
        notes.append("the receive filter is not `all`, so other protocols are blocked")
    if iface.link.state != "up":
        notes.append(f"the link is {iface.link.state or 'unknown'} right now")
    if iface.ptm.chain_ok is False:
        notes.append("the PTM chain is broken, so phc2sys keeps a read-latency residual")
    return notes


def _extts_pin(iface: Interface) -> int:
    """The index of a pin that can be an external timestamp input."""
    for pin in iface.timestamping.pins:
        if pin.func == 1:
            return pin.index
    return 0
